### ISSUE TITLE
[4pt]  Fetch missions - Fetch data

### ISSUE THREAD

**Issue by KaskMIL** [KaskMIL/spacex-reservations#18]
Fetch data from the Missions endpoint  (https://api.spacexdata.com/v3/missions) when a user navigates to the Missions section.

Once the data are fetched, dispatch an action to store the selected data in Redux store:

- mission_id
- mission_name
- description

NOTE: Make sure you only dispatch those actions once and do not add data to store on every re-render (i.e. when changing views / using navigation).

**Comment by Brenda309** [comment]
Hi [@KaskMIL ](https://github.com/Brenda309),

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

### Highlights
No linter errors. ✔️
GitHub flow is followed. ✔️
Professional README file. ✔️
PR has a good title and summary. ✔️

<img src="https://media3.giphy.com/media/fdyZ3qI0GVZC0/giphy.gif"/>

### Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.
