### ISSUE TITLE
Project review

### ISSUE THREAD

**Issue by KaskMIL** [KaskMIL/spacex-reservations#21]
[Project link](https://github.com/KaskMIL/spacex-reservations/projects/1)
We are 3 in the team.
@KaskMIL 
@Brenda309 
@Olamarx

**Comment by KaskMIL** [comment]
Hi @zieeco 
thanks for your review, we'll update the missing card
Cheers, have a good one!

**Comment by KaskMIL** [comment]
Hi @sja-thedude,
thanks for your review, I don't know why it didn't copy all the cards.
Have a good one! cheers

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi Team,

✔️ Correct number of cards

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
